### PR TITLE
Internal Task 15757413: [VSCode] [1DS] Move 1DS Core and 1DS Post to GitHub

### PR DESCRIPTION
**Pull request by MSNev**
- Update publishing and version
- Add typedocs

### CODE REVIEW

**Review by Karlie-777 — APPROVED** [review]

**Comment by AmeyaLokre** [comment]
hey team, where can we find the source code for `microsoft/1ds-post-js@3.2.13` ?

**Comment by Karlie-777** [comment]
hi @AmeyaLokre all previous source code for 1ds post channels are inside our internal repo and they are not public in GitHub.

**Comment by MSNev** [comment]
And for reference the code "mostly" moved as is (ie. the order and functionality of the flow is the same), there were some type refactoring / moving to merge the internal components into this repo, but this did not affect the functionality.

The major difference between v3.x and v4.x (full open sourced) is the support for the dynamic configuration.

If you "really" want to dig into the source code (to validate what I've said above), the npm packages actually "include" the full source code, which was the approach before we took before moving the code here.

See https://www.npmjs.com/package/@microsoft/1ds-post-js/v/3.2.13?activeTab=code and then in the `src` folder.

**Comment by AmeyaLokre** [comment]
thank you for the explanation @Karlie-777 and @MSNev . Will use the npmjs' "code" tab if we end up needing the source code.

**Pull request merged**
