### PR TITLE
[BUG] Telemetry correlation headers are not included for all fetch requests #1240

### PR DESCRIPTION
**Pull request by MSNev**

### CODE REVIEW

**Comment by josundt** [comment]
Please see my additional comments added to the issue; maybe it could all be fixed in this PR:

https://github.com/microsoft/ApplicationInsights-JS/issues/1229#issuecomment-608419912

**Comment by MSNev** [comment]
> Please see my additional comments added to the issue; maybe it could all be fixed in this PR:
> 
> [#1229 (comment)](https://github.com/microsoft/ApplicationInsights-JS/issues/1229#issuecomment-608419912)

After adding specific tests for this my original fix also resolved the Request() argument issues as well -- as the same basic problem was occuring, but I did find that when enabling enableRequestHeaderTracking the headers where not being included either -- now fixed

**Comment by josundt** [comment]
When is the next planned release?
Will this PR be reviewed/accepted/merged before that?
I hope so since it is a blocking bug for many that should be fixed as soon as possible.

**Comment by MSNev** [comment]
I was planning on starting the process for a dot release (2.5.4) as soon as these PR's (tslib and this one) are committed. So this should be fully deployed by the end of the week and optimistically we should have an NPM package later today (PST timezone)

**Pull request merged**
