### PR TITLE
Updating default setting to aiConfig.url to not hardcode http endpoint

### PR DESCRIPTION
**Pull request by AlexBulankou**
Fix for #233

### CODE REVIEW

**Comment by kamilszostak** [comment]
:shipit:

**Comment by fermaem** [comment]
Sorry for asking, but why rather not always posting to https?

**Comment by AlexBulankou** [comment]
@fermaem this is for consistency how our snippet works, but we are actually making the change to always use https soon (next week or so) and when this change is done we will also update static initialization
@kamilszostak FYI

**Comment by fermaem** [comment]
>we are actually making the change to always use https soon

YES :bangbang: :tada: :heart:

Thx for this

**Pull request merged**
