### PR TITLE
Albulank/limit trace messages

### PR DESCRIPTION
**Pull request by AlexBulankou**
Fix for #125

### CODE REVIEW

**Comment by MaxShehovtsov** [comment]
Actually - I thought about it. I'm not sure we want to make this change. Right now users will get 1 trace per page view (so overhead is low). In return they'll get clear diagnostics about why there's no ajaxes reported. I'm not sure it's easy to discover this 1-per-session trace in a huge pile of other traces users might have.
A better long term fix would be to align all internal messages to be 1 per session. This will make them have equal weight in customer's eyes, therefore easier to understand.

Since short term gain is minimal and it makes it harder to troubleshoot, I would not make this change.

**Comment by AlexBulankou** [comment]
I agree with making all diagnostic messages to be one per session. I'll just make this fix instead.

**Comment by MaxShehovtsov** [comment]
I think just making this fix will make things inconsistent.

**Comment by AlexBulankou** [comment]
I meant I will make the fix that you suggested. I should have said "that fix", not "this fix" :)

**Comment by MaxShehovtsov** [comment]
:+1:

**Pull request closed without merging**
