### PR TITLE
Create E2ETests as a directory.

### PR DESCRIPTION
**Pull request by mateoatr**
Create E2ETests as a directory instead of a file by appending '\' to the route.

### CODE REVIEW

**Comment by MaxShehovtsov** [comment]
A commit description would be helpful :)

**Comment by mateoatr** [comment]
@MaxShehovtsov Just did (y). I was having some build errors with the PowerShell script, it seems that if there isn't any '\' at the end of a route, PowerShell will create a blob instead of a directory.

**Comment by dnduffy** [comment]
:shipit:

**Comment by kamilszostak** [comment]
:shipit:

**Pull request merged**
