### PR TITLE
Optimize internal logging

### PR DESCRIPTION
**Pull request by KamilSzostak**
This change will reduce the SDK size by ~1kb (minimized+gzipped).

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Can you pls summarize changes and main ideas of this PR?

**Comment by KamilSzostak** [comment]
Sorry, I know that the change is quite big, but it's mostly find/replace type of changes. The main idea is to reduce the SDK size. The change includes the following parts:
* combine `throwInternalNonUserActionable` and `throwInternalUserActionable` into one `throwInternal(isUserAct=false, ...)` method 
* I create an `_InternalLogMessage` object inside the `throwInternal` method, instead of passing it as a parameter
* remove `USRACT_` and `NONUSRACT_` prefixes from `_InternalMessageId` enum
* cleanup `Initialization.getDefaultConfig()` method

**Comment by SergeyKanzhelev** [comment]
You can also regenerate the schema from public types only like here: https://github.com/Microsoft/ApplicationInsights-node.js/tree/develop/Schema It will remove some internal and legacy types and fields and ultimately make script smaller

**Comment by KamilSzostak** [comment]
Yes, I'm planning to regenerate schema - #327.

**Pull request merged**
