### PR TITLE
Fix #1434 add cookie path

### LINKED ISSUE #1434: Ability to specify cookie Path so that AI works behind App Gateway
Currently when creating cookies, the cookie path is hard-coded to `/`. This breaks cookies when an application using AI Client SDK is placed behind a reverse proxy such as App Gateway product in Azure. Applications behind the reverse proxy are available on sub-paths like /app1, /app2, and so on. Because AI cookies have path as /, they are shared between all apps. This results in the app that was refreshed last overwriting the session cookie for all other apps. That means AI session for the app that gets requested from server the most ends up with all the AI logs, and all other apps have their sessions deleted.

Possible solutions:
1. Do not set cookie path at all, browser will choose the current path to be the default. If AI SDK is initialized by /app1, cookie path will be set to /app1 by the browser, then app1 will track all of its AI cookies without other apps seeing and overwriting them.
2. Set cookie path to "", the behavior is identical to #1
3. Let cookie path be configurable for all cookies. You already have a setting for cookie domain, so you would just need to add one more setting for cookie path

Alternatives I considered:
1. Create our own fork of AI Client SDK and maintain it separately. We can choose to make #1, #2, or #3 change there and push it to our package server, then have everyone in the company use that. Obviously there are some maintenance effort issues with that
2. Implement #3 for this repo and submit it as a pull request. It could add a setting for cookie path and have it be '/' by default for backward compatibility. If set to null, cookie path will not be set (#1). That way the solution is both backward compatible and simple.
3. Write additional code and package it for our applications, that will initialize AI SDK with cookies disabled, and then create our own cookies. That has maintenance effort issues just like alternative #1 even though we avoid modifying AI Client SDK.

### PR DESCRIPTION
**Pull request by 01binary**
Pull request for feature request #1434, adding cookie path to make AI client SDK work behind Azure Application Gateway.

### CODE REVIEW

**Comment by 01binary** [comment]
I am looking at build errors, haven't found what was wrong yet - it's using a built system I am not familiar with.

**Comment by MSNev** [comment]
I'm going to include the ability to set the path as part of #1091 which I'm doing in a working branch (MSNev/CookieHandling) -- note this includes several changes that will be split out into several PR's (i.e. it has an amount of minification work that is making the size of a PR too large) -- it does not yet support the suggested changes yet.

**Comment by MSNev** [comment]
Assigning this PR to myself (so it doesn't get lost/forgotten)

**Comment by 01binary** [comment]
I understand you will use this PR to look at proposed changes but it will never be merged - closing - thank you!

**Pull request closed without merging**
