### PR TITLE
Allow passing severityLevel in trackException

### PR DESCRIPTION
**Pull request by kamilszostak**
#170

### CODE REVIEW

**Comment by abaranch** [comment]
Do you have autocollected exceptions? If yes, do you want to set SeverityLevel for them?..

:shipit:

**Comment by dnduffy** [comment]
:shipit:

**Comment by kamilszostak** [comment]
@abaranch Good point, but I don't want to change the current behavior.

**Comment by abaranch** [comment]
@kamilszostak but that would be consistent with Web SDK where we set it...

**Pull request merged**
