### PR TITLE
common: add tests for canIncludeCorrelationHeader

### PR DESCRIPTION
**Pull request by markwolff**
- Add tests for `canIncludeCorrelationHeader`. 
- minor: Replace `Array.some` logic

### CODE REVIEW

**Comment by markwolff** [comment]
@LeopoldLerch

**Comment by LeopoldLerch** [comment]
I might be wrong, but Array.prototype.forEach is also not supported in IE < 9

**Comment by markwolff** [comment]
Yep you are correct. Moving forward, it might not be feasible to plan for <IE8 support at all.

**Comment by LeopoldLerch** [comment]
If really needed down there they should use polyfills. IE 8 is really old

Mark Wolff <notifications@github.com> schrieb am Mi., 29. Mai 2019, 18:57:

**Pull request merged**
